load("@bazel_tools//tools/build_defs/repo:git.bzl", "new_git_repository")

new_git_repository(
    name = "http_parser",
    remote = "https://github.com/nodejs/http-parser.git",
    tag = "v2.8.1",
    build_file = "BUILD.http_parser",
)
